Django/music_engine/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_engine.urls')),
]

Django/music_engine/music_engine/urls.py
from django.urls import path
from . import views
# from django.conf import Settings

app_name = 'music_engine'

urlpatterns = [
    path('', views.home, name='home'),
    path('display/artists/', views.display_artists, name="display_artists"),
    path('add/artist/', views.add_artist, name="add_artist"),
    path('delete-artist/<int:id>/', views.delete_artist, name="delete_artist"),
    path('update-artist/<int:id>/', views.update_artist, name="update_artist"),
]

Django/music_engine/music_engine/models.py
from django.db import models

# Create your models here.

class Text_Choices():
    Genres = [
        ("Rap","RP", ),
        ("REGGAE", "R&B"),
        ("Hip-Hop","HP"),
        ("SAD","SD")
    ]
    GENDER =[
            ("MALE", "ML"),
            ("FEMALE", "FM"),
    ]


class Artist(models.Model):

    name = models.CharField(max_length=100)
    debut_year = models.DateField()
    gender = models.CharField(choices=Text_Choices.GENDER, default="--")
    age = models.PositiveIntegerField()
    genre = models.CharField(choices=Text_Choices.Genres, default="--")

    def __str__(self):
        return f"{self.name} : {self.age}"
    
class Genre(models.Model):
    genre = models.CharField(max_length=50, choices=Text_Choices.Genres, default="--")

    def __str__(self):
        return f"{self.genre}"

Django/music_engine/music_engine/forms.py
from django import forms
from .models import Artist

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ["name","debut_year","gender","age","genre",]
            
        

Django/music_engine/music_engine/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Artist, Genre
from .forms import ArtistForm
from django.contrib import messages
# Create your views here.

def home(request):
    context = {
    }
    return render(request, 'pages/home.html')

def display_artists(request):
    artists = Artist.objects.all()
    context = {
        "artists": artists
    }
    return render(request, "pages/display.html", context)


def add_artist(request):
    form = ArtistForm()

    if request.method == "POST":
        form = ArtistForm(request.POST)
        if form.is_valid():
            form.save()            
            messages.success(request, "Artist Succesfully Added")
            return redirect('music_engine:display_artists')
    context = {
        "form": form,
    }
    return render(request, "pages/add-artist.html", context)



def delete_artist(request, id):
    try:
        artist = get_object_or_404(Artist, id=id)
        if request.method == "POST":
            artist.delete()
            messages.success(request, "Succesfully Deleted Artist")
            return redirect('music_engine:display_artists')
        return render(request, 'pages/delete-artist.html', {"artist": artist})
    except Artist.DoesNotExist:
        return render(request, 'pages/404.html', context={"error": "Artist does not exist"})
    except Exception as e:
        return render(request, 'pages/505.html', context={f"error": str(e)})
        
def update_artist(request, id):
    try:
        artist = get_object_or_404(Artist, id=id)
        form = ArtistForm(instance=artist)

        if request.method =='POST':
            form = ArtistForm(request.POST, instance=artist)
            if form.is_valid:
                form.save()
                messages.success(request, "Succesfully Updated")
                return redirect('music_engine:display_artists')
        context = {
            "form": form,
            "artist": artist,
                   }
        return render(request, 'pages/update-artist.html', context)
    except Artist.DoesNotExist:
        return render(request, 'pages/404.html', context={"error": "Artist does not exist"})        

Django/music_engine/templates/pages/505.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/errors.css' %}">
</head>
<body>
    <div>
    <P>AN ERROR OCCURED</P>
    <span>{{ error }}</span>
    </div>
</body>
</html>

Django/music_engine/templates/pages/add-artist.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/add-artist.css' %}">
</head>
<body>
    {% include "partials/header.html" %}
    <div>
        <form action="{% url 'music_engine:add_artist' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit">Submit</button>
    </div>
</form>
    
</body>
</html>

Django/music_engine/templates/pages/delete-artist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/delete-artist.css' %}">
</head>
<body>
    <div>
        <h1>Delete Artist</h1>
        <p>Are you sure you want to delete {{ artist.name }}?</p>
        <form method="POST">
        {% csrf_token %}
        <button type="submit" class="yes-button">YES</button>
        <a href="{% url 'music_engine:display_artists' %}" class="no-link">NO</a>
        </form>
    </div>
    
</body>
</html>

Django/music_engine/templates/pages/display.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/display-artist.css' %}">
</head>
<body>
    {% include "partials/header.html" %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert-{{ message.tags}}">
            {{ message }}
            </div>
        {% endfor %}    
    {% endif %}
    
    <div class='artist-container'>
        {% for artist in artists  %}
            <div class='artist'>
                <p>Name-{{ artist.name }}</p><hr>
                <span>Debut Year-{{ artist.debut_year }}</span><hr>
                <span>Gender-{{ artist.gender }}</span><hr>
                <span>Age-{{ artist.age }}</span><hr>
                <span>Artist Genre-{{ artist.genre }}</span>
                <div>
                    <button><a href="{% url 'music_engine:delete_artist' artist.id %}">Delete Artist</a></button>
                    <button><a href="{% url 'music_engine:update_artist' artist.id %}">Update Artist</a></button>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>

Django/music_engine/templates/pages/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
</head>
<body>
{% include "partials/header.html" %}
<div>
    <h1>Music Engine</h1>
    <p>Welcome to Music Engine, a futuristic web app where you can simulate music creation and experience it at the same time</p>
    <a href="{% url 'music_engine:display_artists' %}"><button class="view-button">View artists</button></a>
    <a href="{% url 'music_engine:add_artist' %}"><button class="add-artist-button">Add Artist</button></a>
</div>
    
</body>
</html>

Django/music_engine/templates/pages/update-artist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/add-artist.css' %}">
</head>
<body>
{% include "partials/header.html" %}
    <div>
    <form action="{% url 'music_engine:update_artist' artist.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Update Artist</button>
    
    </form>
    </div>
</body>
</html>

Django/music_engine/templates/partials/header.html
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
{% endblock head %}
{% block content %}
    <nav class="nav-bar">
        <a href="{% url 'music_engine:home' %}"class='nav-link'><span>Home</span></a>
        <a href="{% url 'music_engine:add_artist' %}"class='nav-link'><span>Add Artist</span></a>
        <a href="{% url 'music_engine:display_artists' %}" class='nav-link'><span>View Artists</span></a>
    </nav>
<script src="{% static 'js/nav-script.js' %}"></script>
{% endblock content %}